### ISSUE TITLE
promise is not defined  Error

### ISSUE THREAD

**Issue by cuter74** [nordnet/cordova-hot-code-push-cli#46]
I had to run cordova-hcp deploy

unable to sync: BadRequest: null
    at Request.extractError (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/services/s3.js:322:35)
    at Request.callListeners (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/usr/lib/node_modules/cordova-hot-code-push-cli/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
unable to sync: BadRequest: null

why??

**Comment by nikDemyankov** [comment]
I might be wrong, but it seems that this error states `BadRequest`, not that `promise is not defined`.

Seems like it can't connect to the aws server. And reason for that can be: wrong url, bad credentials. Please, check:

1. That you executed `cordova-hcp init` and it generated correct `cordova-hcp.json` file. Mainly - `content-url` in it, since it should be the address of your aws server.

2. That you executed `cordova-hcp login` and provided correct credentials. It should generate `.chcplogin` file with them.
