### ISSUE TITLE
Android: filenames with spaces lead to fetch error -4

### ISSUE THREAD

**Issue by bbreijer** [nordnet/cordova-hot-code-push-cli#56]
Device: On Android 6.0.1, on an Samsung edge s7
If the filenames with a space in the name exists in the manifest, the download fails with an FileNotFound exception.
Updates work file on iOS (tested on iPhone 6 with iOS 9.3.3).

From Android monitor connected to the device failing the update:

```
08-11 06:39:51.830 15161-15540/app-class W/System.err: java.io.FileNotFoundException: <updateURL>/<file with space>
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.nordnetab.chcp.main.network.FileDownloader.download(FileDownloader.java:76)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.nordnetab.chcp.main.network.FileDownloader.downloadFiles(FileDownloader.java:51)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.nordnetab.chcp.main.updater.UpdateLoaderWorker.downloadNewAndChangedFiles(UpdateLoaderWorker.java:221)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.nordnetab.chcp.main.updater.UpdateLoaderWorker.run(UpdateLoaderWorker.java:121)
08-11 06:39:51.830 15161-15540/app-class W/System.err:     at com.nordnetab.chcp.main.updater.UpdatesLoader$1.run(UpdatesLoader.java:58)
```

**Comment by bbreijer** [comment]
moved to the plugin itself
