### ISSUE TITLE
cordova-hcp build error

### ISSUE THREAD

**Issue by coolara** [nordnet/cordova-hot-code-push-cli#67]
$ cordova-hcp build
Running build
C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\node_modules\winattr\lib\whichLib.js:87
                        throw error;
                        ^

Error: unknown erorr
    at Object.getSync (C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\node_modules\winattr\lib\binding\index.js:44:9)
    at C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\node_modules\winattr\lib\index.js:27:30
    at Object.run (C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\node_modules\winattr\lib\whichLib.js:74:12)
    at Object.getSync (C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\node_modules\winattr\lib\index.js:25:19)
    at statSync (C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\index.js:131:28)
    at Object.isHiddenSync (C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\hidefile\index.js:227:13)
    at prepareFilesHashQueue (C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\dist\build.js:64:21)
    at C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\dist\build.js:28:23
    at C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\recursive-readdir\index.js:64:22
    at C:\Users\kid\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\recursive-readdir\index.js:64:22

**Comment by coolara** [comment]
other project is ok ，thank for answering

**Comment by nikDemyankov** [comment]
As I understand, you are running on the Windows machine. And there is something wrong with `hidefile` package, since it's the one that is crashing.

If `build` command works in other projects - then it's something weird with the project files. Maybe weird rights on some of the files? And that's why `hidefile` is crashing: it can't get access to it. 

You can either change the rights on all `www` files, or remove them one by one until you find the one that breaks everything. Or find on your computer where `cordova-hcp` is installed, go to `dist/build.js` file and add logging on [line 63](https://github.com/nordnet/cordova-hot-code-push-cli/blob/master/dist/build.js#L63) on `file` variable.
